# Generated by Django 5.1.1 on 2024-10-30 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_create', models.DateTimeField(auto_created=True)),
                ('text', models.TextField(max_length=1000)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.messageboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.userboard')),
            ],
        ),
    ]
