# Generated by Django 5.1.1 on 2024-10-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='responses',
            field=models.ManyToManyField(to='models.response'),
        ),
        migrations.AlterField(
            model_name='response',
            name='data_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
