# Generated by Django 5.1.1 on 2024-10-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_messageboard_responses_alter_response_data_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageboard',
            name='responses',
        ),
    ]
