# Generated by Django 5.1.1 on 2024-12-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_response_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='test',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
