# Generated by Django 5.1.1 on 2024-12-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_messageboard_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageboard',
            name='test',
        ),
    ]
